# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0.xci
# IP: The module: 'design_1_rst_ps7_0_150M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0.xci
# IP: The module: 'design_1_rst_ps7_0_150M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/guoxm/isp_fpga/basic_isp/3_yolov3_tiny_acc/zynq_video_stream/vivado_prj/zynq_video.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_150M_0/design_1_rst_ps7_0_150M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
